export const CATEGORIES = [
  { id: 'meistras', label: 'Meistras', emoji: '🔧', description: 'Siūlau savo paslaugas' },
  { id: 'klientas', label: 'Klientas', emoji: '🏠', description: 'Ieškau meistro ar pagalbos' },
  { id: 'pagalbininkas', label: 'Pagalbininkas', emoji: '🤝', description: 'Galiu padėti su darbais' },
]

export const SPECIALIZATIONS = [
  'Santechnika', 'Elektra', 'Statyba', 'Remontas', 'Baldai',
  'Dažymas', 'Valymas', 'Sodininkyste', 'Transportas', 'IT paslaugos',
  'Grožis', 'Sveikata', 'Mokymas', 'Teisė', 'Kita',
]

export const SAMPLE_LISTINGS = [
  {
    id: 1,
    type: 'meistras',
    title: 'Profesionalus santechnikas Vilniuje',
    description: 'Atlieku visus santechnikos darbus: vamzdžių keitimas, čiaupų montavimas, kanalizacijos valymas. 15 metų patirtis. Atvykstu per 2 valandas.',
    author: 'Jonas Kazlauskas',
    location: 'Vilnius',
    specialization: 'Santechnika',
    phone: '+370 612 34567',
    createdAt: '2026-03-13',
    price: 'Nuo 30€/val.',
  },
  {
    id: 2,
    type: 'klientas',
    title: 'Reikia suremontuoti vonios kambarį',
    description: 'Ieškau meistro vonios kambario remontui. Reikia pakeisti plyteles, santechniką ir atnaujinti apšvietimą. Butas Šeškinėje.',
    author: 'Marta Petraitienė',
    location: 'Vilnius, Šeškinė',
    specialization: 'Remontas',
    phone: '+370 698 76543',
    createdAt: '2026-03-12',
    price: 'Biudžetas iki 3000€',
  },
  {
    id: 3,
    type: 'pagalbininkas',
    title: 'Padedu kraustytis ir nešti baldus',
    description: 'Jaunas, stiprus vyrukas. Galiu padėti kraustytis, nešti baldus, tvarkyti sodą ar atlikti kitus fizinius darbus. Turiu automobilį.',
    author: 'Tomas Grigas',
    location: 'Kaunas',
    specialization: 'Transportas',
    phone: '+370 645 12890',
    createdAt: '2026-03-14',
    price: '15€/val.',
  },
  {
    id: 4,
    type: 'meistras',
    title: 'Elektrikas – montavimas ir remontas',
    description: 'Atliekame elektros instaliacijos darbus: laidų tiesimas, jungiklių montavimas, LED apšvietimas, elektros skydinės. Turime licenciją.',
    author: 'Dainius Vaitkus',
    location: 'Klaipėda',
    specialization: 'Elektra',
    phone: '+370 655 44332',
    createdAt: '2026-03-11',
    price: 'Nuo 25€/val.',
  },
  {
    id: 5,
    type: 'klientas',
    title: 'Ieškau baldžiaus virtuvės baldams',
    description: 'Noriu užsakyti individualius virtuvės baldus. Virtuvė apie 12 kv.m. Pageidauju modernaus stiliaus su sala viduryje.',
    author: 'Rūta Jankauskienė',
    location: 'Vilnius, Antakalnis',
    specialization: 'Baldai',
    phone: '+370 610 55678',
    createdAt: '2026-03-10',
    price: 'Biudžetas 4000-6000€',
  },
  {
    id: 6,
    type: 'meistras',
    title: 'Dažymo darbai – sienos, lubos, fasadai',
    description: 'Profesionaliai dažome vidaus ir lauko sienas. Naudojame tik kokybiškas medžiagas. Greitas ir tvarkingas darbas. Nemokama konsultacija.',
    author: 'Andrius Mockus',
    location: 'Šiauliai',
    specialization: 'Dažymas',
    phone: '+370 677 88990',
    createdAt: '2026-03-09',
    price: 'Nuo 5€/kv.m.',
  },
  {
    id: 7,
    type: 'pagalbininkas',
    title: 'Pagalba su sodo darbais',
    description: 'Galiu padėti sutvarkyti sodą: genėti medžius, ravėti lysves, pjauti žolę, sodinti augalus. Turiu savo įrankius.',
    author: 'Lukas Stankevičius',
    location: 'Panevėžys',
    specialization: 'Sodininkyste',
    phone: '+370 633 22110',
    createdAt: '2026-03-14',
    price: '12€/val.',
  },
  {
    id: 8,
    type: 'klientas',
    title: 'Reikia IT specialisto namų tinklui',
    description: 'Ieškau žmogaus, kuris padėtų sukonfigūruoti namų Wi-Fi tinklą, prijungti išmanias kameras ir nustatyti NAS serverį.',
    author: 'Povilas Dambrauskas',
    location: 'Vilnius, Žirmūnai',
    specialization: 'IT paslaugos',
    phone: '+370 699 11223',
    createdAt: '2026-03-13',
    price: 'Derėtina',
  },
]
